import type { DailyReview, Trade, TradeScreenshot } from "@/types/database";

const MOCK_USER = "mock-user-id";

export const mockScreenshots: TradeScreenshot[] = [
  {
    id: "ss1",
    trade_id: "t1",
    user_id: MOCK_USER,
    image_url: "https://placehold.co/800x420/1a1f2e/88aaff?text=Before+entry",
    image_path: "mock/t1/before.png",
    type: "before_entry",
    caption: "Structure + FVG aligned",
    created_at: "2026-05-01T14:02:00Z",
  },
  {
    id: "ss2",
    trade_id: "t1",
    user_id: MOCK_USER,
    image_url: "https://placehold.co/800x420/1a1f2e/aaff88?text=After+exit",
    image_path: "mock/t1/after.png",
    type: "after_exit",
    caption: "Partial at 1R, runner stopped at BE",
    created_at: "2026-05-01T15:21:00Z",
  },
];

export const mockTrades: Trade[] = [
  {
    id: "t1",
    user_id: MOCK_USER,
    date: "2026-05-01",
    symbol: "ES",
    direction: "long",
    entry_price: 5320.25,
    exit_price: 5326.5,
    stop_loss: 5317,
    risk_amount: 250,
    pnl: 420,
    r_multiple: 1.68,
    setup: "London open trend",
    session: "London",
    emotion: "calm",
    confidence_score: 7,
    discipline_score: 8,
    notes: "Sized down; followed plan.",
    what_went_right: "Waited for reclaim; partials at OB.",
    what_went_wrong: "Almost moved stop early — caught myself.",
    lesson_learned: "Rules > noise on the tape.",
    tags: ["indices", "trend"],
    mistake_tags: [],
    created_at: "2026-05-01T15:30:00Z",
    updated_at: "2026-05-01T15:30:00Z",
  },
  {
    id: "t2",
    user_id: MOCK_USER,
    date: "2026-05-01",
    symbol: "NQ",
    direction: "short",
    entry_price: 18820,
    exit_price: 18845,
    stop_loss: 18860,
    risk_amount: 300,
    pnl: -320,
    r_multiple: -1.07,
    setup: "Breakdown failure",
    session: "NY",
    emotion: "frustrated",
    confidence_score: 5,
    discipline_score: 4,
    notes: "Chased weakness; should have waited.",
    what_went_right: "Stopped when invalidation hit.",
    what_went_wrong: "Entered before confirm.",
    lesson_learned: "No entry without trigger candle.",
    tags: ["indices", "reversal"],
    mistake_tags: ["early entry"],
    created_at: "2026-05-01T18:05:00Z",
    updated_at: "2026-05-01T18:05:00Z",
  },
  {
    id: "t3",
    user_id: MOCK_USER,
    date: "2026-05-02",
    symbol: "AAPL",
    direction: "long",
    entry_price: 210.4,
    exit_price: 211.35,
    stop_loss: 209.85,
    risk_amount: 200,
    pnl: 380,
    r_multiple: 1.9,
    setup: "Opening drive",
    session: "NY",
    emotion: "focused",
    confidence_score: 8,
    discipline_score: 9,
    notes: "",
    what_went_right: "Aligned with broad market.",
    what_went_wrong: "",
    lesson_learned: "Repeat the process.",
    tags: ["equities", "opening"],
    mistake_tags: [],
    created_at: "2026-05-02T14:45:00Z",
    updated_at: "2026-05-02T14:45:00Z",
  },
  {
    id: "t4",
    user_id: MOCK_USER,
    date: "2026-05-03",
    symbol: "ES",
    direction: "short",
    entry_price: 5340,
    exit_price: 5331.25,
    stop_loss: 5346,
    risk_amount: 250,
    pnl: 290,
    r_multiple: 1.16,
    setup: "NY afternoon fade",
    session: "NY",
    emotion: "neutral",
    confidence_score: 6,
    discipline_score: 7,
    notes: "",
    what_went_right: "",
    what_went_wrong: "",
    lesson_learned: "",
    tags: ["fade"],
    mistake_tags: [],
    created_at: "2026-05-03T19:40:00Z",
    updated_at: "2026-05-03T19:40:00Z",
  },
  {
    id: "t5",
    user_id: MOCK_USER,
    date: "2026-05-05",
    symbol: "NQ",
    direction: "long",
    entry_price: 18690,
    exit_price: 18655,
    stop_loss: 18670,
    risk_amount: 350,
    pnl: -410,
    r_multiple: -1.17,
    setup: "VWAP reclaim",
    session: "NY",
    emotion: "impulsive",
    confidence_score: 4,
    discipline_score: 3,
    notes: "",
    what_went_right: "",
    what_went_wrong: "Traded news spike.",
    lesson_learned: "Sit out first 5 after headline.",
    tags: ["news"],
    mistake_tags: ["news trading"],
    created_at: "2026-05-05T13:15:00Z",
    updated_at: "2026-05-05T13:15:00Z",
  },
  {
    id: "t6",
    user_id: MOCK_USER,
    date: "2026-05-08",
    symbol: "ES",
    direction: "long",
    entry_price: 5295,
    exit_price: 5308,
    stop_loss: 5288,
    risk_amount: 280,
    pnl: 520,
    r_multiple: 1.86,
    setup: "London open trend",
    session: "London",
    emotion: "calm",
    confidence_score: 8,
    discipline_score: 8,
    notes: "",
    what_went_right: "",
    what_went_wrong: "",
    lesson_learned: "",
    tags: ["trend"],
    mistake_tags: [],
    created_at: "2026-05-08T08:55:00Z",
    updated_at: "2026-05-08T08:55:00Z",
  },
];

export const mockDailyReviews: DailyReview[] = [
  {
    id: "dr1",
    user_id: MOCK_USER,
    date: "2026-05-01",
    discipline_score: 6,
    emotional_rating: 6,
    biggest_mistake: "Early short without confirmation.",
    lesson_learned: "Define invalidation before click.",
    notes: "Solid morning, sloppy afternoon.",
    created_at: "2026-05-01T21:00:00Z",
    updated_at: "2026-05-01T21:00:00Z",
  },
];

export function getScreenshotsForTrade(tradeId: string): TradeScreenshot[] {
  return mockScreenshots.filter((s) => s.trade_id === tradeId);
}
